### PR TITLE
changed regexp to support categorization of packets by subdirectories

### PR DESCRIPTION
**Pull request by Yehonal**
now you can use this kind of packet names*:

vendor/lib/name
vendor/view/template/name

jquery/ui
jquery/core

etc.

*relative pull request for bower/bower repository is required

### CODE REVIEW

**Comment by sheerun** [comment]
Tests please

**Comment by Yehonal** [comment]
1 year ago..

**Comment by sheerun** [comment]
better late than never :)

**Comment by sheerun** [comment]
Actually #11 might be a better solution

**Comment by sheerun** [comment]
Moved to bower/bower https://github.com/bower/bower/issues/2308

**Pull request closed without merging**
